language: python
python:
- '3.5'
build:
- make build
script:
- make test
- pip install codacy-coverage && python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: justinbarrick
  on:
    branch: master
    tags: true
env:
  global:
    secure: I1Ianr61As+/ub/7xL6+nQOVd804f1ZiKN9V5VJA1DP50k9mkhc4y2SWnOQiNw872SNvcf+UgaDvofEv7R8kdbl1StRpsIKhiOCUPyqG02TGVCXOIOS8Z5gWC3FvmC/kSHYYpSHvkeOrox9VGf8MvWMHkK3k3TyycpFgHpPvaY0a9ID3DjmoXQgDc19pT8NXZhw9/vbSxrpR8Eaopx8BMZrNkUhnT7w+V3Ikz+/xJE/wGSWHEWHDvmGG5oDdIDBpWuZv4upFw60VwtVj6Y1wGWnMwRDaw3J7/BmOco0z7L3wEG+oXmtYI9cruUu9qRS0IdKqYlxAAOE4RRvyVLAODVjeZ5cPlea443FCjFl90yiV4qHAOX6u50KYSQePEJ6nhOl7kWGbT1mB+TIg+2Nh+Hvx3+9cNOOvr3gKjLwU6hoFxDaY2iU1vIrR0tA5KMMQ4AtI6ZH7yS7YwzMqCYu/Jp0NkBJiKz3Iq/eJtoiux2vMOIQSUohdB7Eu+8RCACBKI7aApfOeDlAdIpKaXsGOwcGz6wkKmNM06UpgcEdUCX1o7XTBM8lwWItAeKfvmTLXCip4MZQMHB3cnqN2MOOFF4RaFqn2yMBjjRXdvRYw4QEX7GwcV2VxMSfwU4ZtOiVPeXKbEB7n3jfIPqiqDVvlp/SgHGiEoETCZNFTg78Jz90=
dd:
  secure: V2jaAnMBl9x35DekPQSCZ+4mQls+sfqTh073inktqGlHO+qGsPG/xAcmgAJYaIaMsrv4KXh8TouCMuInFlGhBewhKPV0zlhlqSxG+6ZzPmdSwZfaP7JOTCNODbd5qn5HNS7NO0W50pIvOycK6L3k53Kfy7yQSVAGk3epy1ju3XSQVbM0uOyT2uWIUBXc3z+T7hn46g+7hSYJcy8/ft5P9Hpy26d7WdAtt6A/bP2SGIjItLX5EOaa2H6iMaF1IbMNMNt6KGYd8A+ThCd/QDduVLADhv/QCIArPQDnW6GskJB/B61XDPLvDqzsZ7Zmy6zP0SG4ulTGYu8hIs2hJSYPlPJ5bd4KAtYAHPgYsa4N8w0Tuh0fJQBAOvyBrfqjLk2lEXYk9DxRANY50y40KI7quW1R4O1SKKiWFbB2nZXK2pjtxASV2+dgfSD1mr5r283jc+18k0dCqFQz1ZWN2SmwAOWPAEqEz7wJB0hfA+l8pkX7xZNQp9yWZQ8aNCy6iqNEBLP/PDGRoqsep71SgjPLoMa5biONwuHr2mVqK1YFY30BmfpTCepToR/HHzVzd29GKUWYvd7c1sY342iUbcrokcVBN6mjeG3105pFsNP2hlZ6ir2LTDCcaqQ9Nw5nPN46Yo8nefHzGHGScPqECzmZqOw/NJamDpS/PsN64tigBsY=
