language: python
python:
- '3.5'
build:
- make build
script:
- make test
- pip install codacy-coverage && python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: justinbarrick
  password:
    secure: MlKtZu0k7G7QcmWqrskLrpyC9SpuiZP73SuvbT9NDR/kQDK2Y+eRZoFVm3P9NYeB5PYGWMrwkRvzlHOvT5skIg9gNCO7PnQv31VNRLxHNmri/Gz+WLBFC2+xYIwc4xRIIyatPFf4t/BpX1GdL4zUV+dNGG1TNrMk3gw7WSrWPF42odw6ziecRYR88GUsigoCB89UtacMIRxSN+vHy7aaaNrLbhhLrZDQM8opG9ZORLfrszSD2YXi8z5zuCmXh2ltAl6gBPCMWaNUriXvC7vE33PpOlFp4m5wsy31MV1vuiNCXO7hOIYz32AOlIdTKMUX0MfechNTZUU40GLJUWA1xzgY3kBzWn0SCTgCXbMO8ye042An/t1wiN1A+IMZmBeVb0Ta+RWKEkCsNYT7g6TxNu/7uV6l5AMkcEjFtVuITIyazIxHbp/DSUMyjSYie6upJUZxfdz0DNAUIFrIRUohhAZRAmzNzCvhjsADEKWn1J4FK1j1xSafeYnlWVKhaYz09KU+6GyXhIzSI118IHFpNS7GwB3xD2sxjDhFkD1ukFIF/DAJbqG0LxjiQjmPLk+kRDy4EPqQkxmKpEEnLNXxV0gcC+Ft7ubc263K1BXqwnSigZWnRK7L2g4BNNE47NG0aIzHE2Y8RMn9tBkb8vTVljn7NdTamonFu3+68QXBhAM=
  on:
    branch: master
    tags: true
env:
  global:
    secure: I1Ianr61As+/ub/7xL6+nQOVd804f1ZiKN9V5VJA1DP50k9mkhc4y2SWnOQiNw872SNvcf+UgaDvofEv7R8kdbl1StRpsIKhiOCUPyqG02TGVCXOIOS8Z5gWC3FvmC/kSHYYpSHvkeOrox9VGf8MvWMHkK3k3TyycpFgHpPvaY0a9ID3DjmoXQgDc19pT8NXZhw9/vbSxrpR8Eaopx8BMZrNkUhnT7w+V3Ikz+/xJE/wGSWHEWHDvmGG5oDdIDBpWuZv4upFw60VwtVj6Y1wGWnMwRDaw3J7/BmOco0z7L3wEG+oXmtYI9cruUu9qRS0IdKqYlxAAOE4RRvyVLAODVjeZ5cPlea443FCjFl90yiV4qHAOX6u50KYSQePEJ6nhOl7kWGbT1mB+TIg+2Nh+Hvx3+9cNOOvr3gKjLwU6hoFxDaY2iU1vIrR0tA5KMMQ4AtI6ZH7yS7YwzMqCYu/Jp0NkBJiKz3Iq/eJtoiux2vMOIQSUohdB7Eu+8RCACBKI7aApfOeDlAdIpKaXsGOwcGz6wkKmNM06UpgcEdUCX1o7XTBM8lwWItAeKfvmTLXCip4MZQMHB3cnqN2MOOFF4RaFqn2yMBjjRXdvRYw4QEX7GwcV2VxMSfwU4ZtOiVPeXKbEB7n3jfIPqiqDVvlp/SgHGiEoETCZNFTg78Jz90=
