language: python
python:
- '3.5'
build:
- make build
script:
- make test
- pip install codacy-coverage && python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: justinbarrick
  password:
    secure: fa7DhQhEw7pflqGOkCTxy2IzjB8syfwSJFGjGZLIFuRiZ0KwwLYyxdCVytNRPf9tp1jVyux05hAAfho9JkXk9Ncjic5nCsc08lrB5277ZokJUYIYL5c4kq3NEfiLoVXKHJjzTuk0cksSrUtSJ1O0zWGZCbidB9o+SiXUCkmEZO+yJ0Ogb1fIqJO0cxV5y2tHWoiN2k6CUWqUVwkPkEjZ6g6B69u4XNpplMj+Yf0QlWXkOSnnL0PnlvL9uc9Z672XZsCtBJj1H4LWLwtDkb1/YXeR9Sh79t2ZYyziDJQ8Mg+gGWQ7WwxwDMDWEqSWNpOwRg6GB69rrdjiLlUKrv82atPwDBk0icBcINrMAyoV2/tdNnhGL5hJTz7btSdS2q+DrHfbuKdm2L8ZqO7wNNouUGOYWTXDah9SHX9ApW6kRwWAef+UMrxA0JyREvbveq95bMeC7ZCAUtUY+ySZJzRCevJwyxggO8rwHi6VskkB3DsuvaPu3OiiCG9dR+o6FlhOHIIqoolbYyJuchy84XppjB6xe5oLcXsX5b2yaaKnP0R7+8Lfs1psvMZb5E86Z1MGZqkWAxGfkf6MiUxTQHkzDvGFy0wbVqhY2aBAQWIgF1ZVZVfQhprugdlhGERQsKItO/EMKyRVkoOr0Sf3axdUXCWsVK+exfwpGKSL1z/Za0E=
  on:
    branch: master
    tags: true
env:
  global:
    secure: I1Ianr61As+/ub/7xL6+nQOVd804f1ZiKN9V5VJA1DP50k9mkhc4y2SWnOQiNw872SNvcf+UgaDvofEv7R8kdbl1StRpsIKhiOCUPyqG02TGVCXOIOS8Z5gWC3FvmC/kSHYYpSHvkeOrox9VGf8MvWMHkK3k3TyycpFgHpPvaY0a9ID3DjmoXQgDc19pT8NXZhw9/vbSxrpR8Eaopx8BMZrNkUhnT7w+V3Ikz+/xJE/wGSWHEWHDvmGG5oDdIDBpWuZv4upFw60VwtVj6Y1wGWnMwRDaw3J7/BmOco0z7L3wEG+oXmtYI9cruUu9qRS0IdKqYlxAAOE4RRvyVLAODVjeZ5cPlea443FCjFl90yiV4qHAOX6u50KYSQePEJ6nhOl7kWGbT1mB+TIg+2Nh+Hvx3+9cNOOvr3gKjLwU6hoFxDaY2iU1vIrR0tA5KMMQ4AtI6ZH7yS7YwzMqCYu/Jp0NkBJiKz3Iq/eJtoiux2vMOIQSUohdB7Eu+8RCACBKI7aApfOeDlAdIpKaXsGOwcGz6wkKmNM06UpgcEdUCX1o7XTBM8lwWItAeKfvmTLXCip4MZQMHB3cnqN2MOOFF4RaFqn2yMBjjRXdvRYw4QEX7GwcV2VxMSfwU4ZtOiVPeXKbEB7n3jfIPqiqDVvlp/SgHGiEoETCZNFTg78Jz90=
