language: python
python:
- '3.5'
build:
- make build
script:
- make test
- pip install codacy-coverage && python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: justinbarrick
  password:
    secure: J5z65coETkSS8BImS25Q0Tvu4lKVUoezjfcULpTr3w5Lu402NB14bjTZn70TvHuVEci8mgdDi0DzTQSu/yEMDyc+qEIqqgTcmOHIARWCmFg1KBB9dJLGzfyzUk/KOLjjoxgX0/Oz/A927yXHK4jk44fwgscm9BhNQVPBrW6XlespjS7j7JaKWkQnVoA/a8RZ0K5CurbFX2bCsehtRDvMBO4kfNj1bSb+U6NAdA9Sck1UlLlR5SbNNDLkgAc1OxbaCdiWq4OAKidtijzUsrK6rQ9/5R4IOqHuVMMVZkzuHb2/57AY/T3jbVvvrAweVQOc94ZZgAyB5t6WxL2GlDYA3Evl3Sspprrl2ms+vMrALX4bk5X/n6YTL/UdOKcp090mlqd485kMNpSer+PTlHlDEh/oFb/2A+nIMP1cswEKZDgLoGcdCYNmc097AulQHXNq3MhkAAOl0jFShd8xlG+c3arN+8+O5vy8HvXkxuemU3D67zYyDmEIp/ogeN94KqPZ9ErIQV2ZYdQ7d+woM+eVly5GZPBH4X1zsZjtp0BRRNPwftnqQEF5INHDcP4rH6+hG65j1tkUZdeSSd2D3GzpP9PefjzD7eoogEZdOWV1hRw8uNthtuMucowgIXDILKdci1X0DsS5oFzO80zsf4KhI5lkit+BniasCszjLiNth1M=
  on:
    tags: true
env:
  global:
    secure: I1Ianr61As+/ub/7xL6+nQOVd804f1ZiKN9V5VJA1DP50k9mkhc4y2SWnOQiNw872SNvcf+UgaDvofEv7R8kdbl1StRpsIKhiOCUPyqG02TGVCXOIOS8Z5gWC3FvmC/kSHYYpSHvkeOrox9VGf8MvWMHkK3k3TyycpFgHpPvaY0a9ID3DjmoXQgDc19pT8NXZhw9/vbSxrpR8Eaopx8BMZrNkUhnT7w+V3Ikz+/xJE/wGSWHEWHDvmGG5oDdIDBpWuZv4upFw60VwtVj6Y1wGWnMwRDaw3J7/BmOco0z7L3wEG+oXmtYI9cruUu9qRS0IdKqYlxAAOE4RRvyVLAODVjeZ5cPlea443FCjFl90yiV4qHAOX6u50KYSQePEJ6nhOl7kWGbT1mB+TIg+2Nh+Hvx3+9cNOOvr3gKjLwU6hoFxDaY2iU1vIrR0tA5KMMQ4AtI6ZH7yS7YwzMqCYu/Jp0NkBJiKz3Iq/eJtoiux2vMOIQSUohdB7Eu+8RCACBKI7aApfOeDlAdIpKaXsGOwcGz6wkKmNM06UpgcEdUCX1o7XTBM8lwWItAeKfvmTLXCip4MZQMHB3cnqN2MOOFF4RaFqn2yMBjjRXdvRYw4QEX7GwcV2VxMSfwU4ZtOiVPeXKbEB7n3jfIPqiqDVvlp/SgHGiEoETCZNFTg78Jz90=
